// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmxwjgkplcubaqyvunmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteHdqZ2twbGN1YmFxeXZ1bm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDk5MjQsImV4cCI6MjA1ODM4NTkyNH0.uqGkLy5sRsITYALWI8IqRAExVv-fdbiVF4Ppas4487M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);